### ISSUE TITLE
plotvector.py is loaded as a plugin by sublime

### ISSUE THREAD

**Issue by tbrlpld** [tibsel/PlotGraph#7]
This is causing some errors:
```
...
reloading plugin Package Control.Package Control
reloading plugin PlotGraph.plotgraph
reloading plugin PlotGraph.plotvectors
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\tibor\AppData\Roaming\Sublime Text 3\Packages\PlotGraph\plotvectors.py", line 5, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named 'matplotlib'
plugins loaded
...
```

According to the [unofficial sublime documentation](http://docs.sublimetext.info/en/latest/extensibility/plugins.html) files that are nested in any subdirectory of the package are not loaded as plugins. 

This means it should be enough to just add another folder and move the plotvrector.py into it.

**Comment by tbrlpld** [comment]
Fixed in commit [7d7b372](https://github.com/tibsel/PlotGraph/commit/7d7b3723ebefc8537b1c2df18c386cb54a2ea774) on "development" branch.
Will be included in next release.

Errors on import of plugins are not showing in the sublime console anymore.
